ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # Keeps the robot on the flat ground
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Use the IMU for orientation (Yaw) and acceleration
    imu0: /imu/data
    imu0_config: [false, false, false, # x, y, z pose
                  true,  true,  true,  # roll, pitch, yaw
                  false, false, false, # x, y, z velocity
                  true,  true,  true,  # roll, pitch, yaw velocity
                  true,  false, false] # x, y, z acceleration

    # Use Cmd_Vel as a "fake" velocity input since we don't have encoders yet
    twist0: /cmd_vel
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  false, false, # x velocity (forward)
                    false, false, true,  # yaw velocity (turning)
                    false, false, false]