teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1            # Left Stick Up/Down
    scale_linear:
      x: 0.5          # Max speed (m/s)
    axis_angular:
      yaw: 0          # Left Stick Left/Right
    scale_angular:
      yaw: 1.0        # Max turn speed (rad/s)
    enable_button: 0  # Require holding 'X' or 'A' to drive (Safety!)